import { 
  Clock, 
  Lamp, 
  Volume2, 
  Camera, 
  MousePointer2, 
  Keyboard, 
  Lightbulb, 
  Square, 
  Headphones, 
  Smartphone, 
  Video, 
  Watch, 
  Gamepad2, 
  Key, 
  Trees, 
  Scissors, 
  Flashlight, 
  Wind, 
  Home, 
  BatteryCharging, 
  Sparkles, 
  Flame, 
  Shield, 
  Fan, 
  Shirt, 
  MoreHorizontal,
  Package,
  Image,
  Gem,
  Gift
} from 'lucide-react';

export const CATEGORIES = [
  { id: 'keychain', name: 'Keychain', icon: Key },
  { id: 'showpiece', name: 'Showpiece', icon: Gift },
  { id: 'lomo-card', name: 'Lomo Card', icon: Image },
  { id: 'mystery-box', name: 'Mystery Box', icon: Package },
  { id: 'mirror', name: 'Mirror', icon: Sparkles },
  { id: 'ring', name: 'Ring', icon: Gem },
  { id: 'clock', name: 'Clock', icon: Clock },
  { id: 'lamp', name: 'Lamp', icon: Lamp },
  { id: 'speaker', name: 'Speaker', icon: Volume2 },
  { id: 'tripod', name: 'Tripod', icon: Camera },
  { id: 'mouse', name: 'Mouse', icon: MousePointer2 },
  { id: 'keyboard', name: 'Keyboard', icon: Keyboard },
  { id: 'lighting', name: 'Lighting', icon: Lightbulb },
  { id: 'table-lamp', name: 'Table Lamp', icon: Lamp },
  { id: 'mouse-pad', name: 'Mouse Pad', icon: Square },
  { id: 'headset', name: 'Headset', icon: Headphones },
  { id: 'mobile-stand', name: 'Mobile Stand', icon: Smartphone },
  { id: 'cc-camera', name: 'CC Camera', icon: Video },
  { id: 'smart-watch', name: 'Smart Watch', icon: Watch },
  { id: 'watch', name: 'Watch', icon: Watch },
  { id: 'toys', name: 'Toys', icon: Gamepad2 },
  { id: 'key-ring', name: 'Key Ring', icon: Key },
  { id: 'wooden', name: 'Wooden', icon: Trees },
  { id: 'trimmer', name: 'Trimmer', icon: Scissors },
  { id: 'torch-light', name: 'Torch Light', icon: Flashlight },
  { id: 'mobile-cover', name: 'Mobile Cover', icon: Smartphone },
  { id: 'humidifier', name: 'Humidifier', icon: Wind },
  { id: 'room-decoration', name: 'Room Decoration', icon: Home },
  { id: 'power-bank', name: 'Power Bank', icon: BatteryCharging },
  { id: 'mobile-cooler', name: 'Mobile Cooler', icon: Fan },
  { id: 'cosmetics', name: 'Cosmetics', icon: Sparkles },
  { id: 'hot-offer', name: 'Hot Offer', icon: Flame },
  { id: 'self-defence', name: 'Self Defence', icon: Shield },
  { id: 'airbud', name: 'Airbud', icon: Headphones },
  { id: 'fan', name: 'Fan', icon: Fan },
  { id: 't-shirt', name: 'T Shirt', icon: Shirt },
  { id: 'other', name: 'Other', icon: MoreHorizontal },
];
